<div class="content-page">
	<div class="content-page__header">
		<h1 class="content-page__title">Usuários</h1>
		<div class="content-page__toolbar">
			<button type="button" onclick="carregarTela('../../usuario/cadastro')" class="btn btn-primary"><i class="fa fa-plus" aria-hidden="true"></i> Novo Usuário</button>
			<button type="button" onclick="carregarTela('../../usuario/login')" class="btn btn-primary"><i class="fa fa-sign-in" aria-hidden="true"></i> Histórico Login</button>
		</div>
	</div>

	<div class="table-responsive">
		<table class="table table-hover" id="table_usuarios">
			<thead>
				<tr>
					<th></th>
					<th class="text-left">NOME</th>
					<th class="text-left">E-MAIL</th>
					<th class="text-left">PERFIL</th>
				</tr>
			</thead>
			<tbody>
				<?
				if (count($this->registros) > 0): foreach ($this->registros as $key => $value):
				?>
						<tr>
							<td class="text-center" width="60px">
								<div class="btn-group">
									<a class="btn btn-primary" href="#" onclick="carregarTela('../../usuario/cadastro?id_usuario=<?= $value['id_usuario'] ?>')"><i class="fa fa-pencil-square-o"></i></a>
									<a class="btn btn-danger" href="#" onclick="remover('usuario',<?= $value['id_usuario'] ?>,'<?= $value['nome'] ?>')"><i class="fa fa-trash-o"></i></a>
								</div>
							</td>
							<td class="text-left align-middle"><?= $value['nome'] ?></td>
							<td class="text-left align-middle"><?= $value['email'] ?></td>
							<td class="text-left align-middle"><?= $value['descricao_perfil'] ?></td>
						</tr>
				<? endforeach;
				endif; ?>
			</tbody>
		</table>
	</div>
</div>

<script type="text/javascript">
	$(document).ready(function() {
		$('#table_usuarios').DataTable({
			language: {
				url: 'https://cdn.datatables.net/plug-ins/1.10.19/i18n/Portuguese-Brasil.json'
			},
			"columnDefs": [{
				orderable: false,
				targets: [0]
			}],
			"order": [
				[1, 'asc']
			]
		});
	});
</script>
