<div class="content-page">
	<div class="content-page__header">
		<h1 class="content-page__title">Histórico Login</h1>
		<div class="content-page__toolbar">
			<button type="button" onclick="carregarTela('../../usuario/cadastro')" class="btn btn-primary"><i class="fa fa-plus" aria-hidden="true"></i> Novo Usuário</button>
			<button type="button" onclick="carregarTela('../../usuario')" class="btn btn-primary"><i class="fa fa-user-circle-o" aria-hidden="true"></i> Usuários</button>
		</div>
	</div>

	<div class="table-responsive">
		<table class="table table-hover table-condensed">
			<thead class="label-info">
				<tr>
					<th class="text-left">NOME</th>
					<th class="text-left">E-MAIL</th>
					<th class="text-left">PERFIL</th>
					<th>DATA E HORA</th>
				</tr>
			</thead>
			<tbody id="corpo">
				<?
				if (count($this->registros) > 0): foreach ($this->registros as $key => $value):
				?>
						<tr>
							<td class="text-left align-middle"><?= $value['nome'] ?></td>
							<td><span class="invisible login-data-invisivel"><?= $value['data_hora'] ?></span><?= Util::formatData($value['data_hora']) . ' ' . Util::formatHora($value['data_hora']) ?></td>
							<td class="text-left align-middle"><?= $value['email'] ?></td>
							<td class="text-left align-middle"><?= $value['descricao_perfil'] ?></td>
						</tr>
				<? endforeach;
				endif; ?>
			</tbody>
		</table>
	</div>
</div>
<script type="text/javascript">
	$(document).ready(function() {
		$('table').DataTable({
			language: {
				url: 'https://cdn.datatables.net/plug-ins/1.10.19/i18n/Portuguese-Brasil.json'
			},
			"columnDefs": [],
			"order": [
				[1, 'desc']
			]
		});
	});
</script>
