<div class="content-page">
    <div class="content-page__header">
        <h1 class="content-page__title">Alteração de Senha</h1>
        <div class="content-page__toolbar">
            <button type="button" onclick="carregarTela('../../dashboard')" class="btn btn-danger"><i class="fa fa-close" aria-hidden="true"></i> Cancelar</button>
        </div>
    </div>

    <form id="formulario_usuario" method="POST" action="../../index/novasenha">
        <div class="section-card">
            <div class="row">
                <div class="form-group col-md-4">
                    <span><label for="senhaAtual">Senha Atual: </label></span>
                    <input class="form-control" name="senhaAtual" type="password" id="senhaAtual" maxlength="20">
                </div>
                <div class="form-group col-md-4">
                    <span><label for="novaSenha">Nova Senha: </label></span>
                    <input class="form-control" name="novaSenha" type="password" id="novaSenha" maxlength="20">
                </div>
                <div class="form-group col-md-4">
                    <span><label for="confirmaSenha">Confirmar Nova Senha: </label></span>
                    <input class="form-control" name="confirmaSenha" type="password" id="confirmaSenha" maxlength="20">
                </div>
                <div class="form-group col-md-4" hidden>
                    <span><label for="id_usuario">ID Usuário: </label></span>
                    <input class="form-control" name="id_usuario" type="text" value="<?= $this->idUsuario ?>" id="id_usuario">
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12 section-actions">
                <button class="btn btn-success"><i class="fa fa-floppy-o fa-lg"></i> Salvar</button>
            </div>
        </div>
    </form>
</div>
<script type="text/javascript">

    $(document).ready(function() {
        $('#senhaAtual').focus();
    });

    $("#formulario_usuario").submit(function(e) {

        var erro = "";

        if ($('#senhaAtual').val().trim() == "" || $('#novaSenha').val().trim() == "" || $('#confirmaSenha').val().trim() == "") {
            erro = 'Informe todos os campos para salvar a nova senha!';
        }

        if ($('#novaSenha').val().trim() != $('#confirmaSenha').val().trim()) {
            erro = 'As senhas não conferem!';
        }

        if (erro != "") {
            swal({
                title: "Atenção!",
                text: erro,
                type: "error"
            });
            return false;
        }
    });
</script>
