<div class="content-page">
    <div class="content-page__header">
        <h1 class="content-page__title">Dashboard</h1>
    </div>
    <main class="col-sm-12 col-md-12 m-0">
        <a class="btn btn-info" id="material" href="#">Material de Apoio e Videos</a>
        <h1>Em construçaõ</h1>
    </main>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $('#material').on('click', function() {
            carregarTela('../../../dashboard/material');
        });
    });
</script>
