 <div class="d-flex justify-content-center justify-content-md-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
     <h2 class="h2 text-info">Material de Apoio e Videos</h2>
 </div>
 <main class="col-sm-12 col-md-12 m-0">
     <a class="btn btn-info" id="dashboard" href="#">Início</a>
 </main>
 <script type="text/javascript">
     $(document).ready(function() {
         $('#dashboard').on('click', function() {
             carregarTela('../../../dashboard');
         });
     });
 </script>