<div class="content-page">
    <div class="content-page__header">
        <h1 class="content-page__title">Material de Apoio e Videos</h1>
    </div>
    <main class="col-sm-12 col-md-12 m-0">
        <a class="btn btn-info" id="dashboard" href="#">Início</a>
    </main>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $('#dashboard').on('click', function() {
            carregarTela('../../../dashboard');
        });
    });
</script>
