<input name="id_empresa" type="hidden" value="<?= $this->empresa ? $this->empresa['id_empresa'] : '' ?>" id="id_empresa">

<div class="row">
    <div class="form-group col-md-11">
        <span><label for="titulo">Nome: </label></span>
        <input required class="form-control" name="titulo" type="text" value="<?= $this->empresa ? $this->empresa['titulo'] : '' ?>" id="titulo">
    </div>
    <div class="form-group col-md-1">
        <span><label for="titulo">Cor: </label></span><br>
        <input class="form-control" id="cor" name="cor" value="<?= $this->empresa ? $this->empresa['cor'] : '' ?>" />
    </div>
</div>

<? if ($this->empresa): ?>
    <div class="row">
        <div class="form-group col-md-9">
            <span><label for="token">Token: </label></span>
            <input disabled class="form-control" type="text" value="<?= Token::gerarToken($this->empresa['id_empresa']) ?>" id="token">
        </div>
        <div class="form-group col-md-3">
            <span><label for="link">Link: </label></span>
            <a class="btn btn-primary d-block w-100" target="_blank" id="link" href="<?= Empresa::urlSite($this->empresa['id_empresa']) ?>"><i class="fa fa-eye"></i> Acessar o Site</a>
        </div>
    </div>
<? endif; ?>

<div class="row">
    <div class="col-md-12 form-group imageupload">
        <span><label for="titulo">Logo: (Recomendado 700x200)</label></span>
        <div class="file-tab">
            <label class="btn btn-file" style="padding:0">
                <img id="img_logo" alt="Clique para adicionar o Logo da empresa" class="img-fluid thumbnail border" src="<?= $this->empresa ? $this->empresa['logo'] : '' ?>">
                <!-- The file is stored here. -->
                <input type="file">
            </label>
            <input required id="logo_empresa" type="hidden" name="logo" value="">
        </div>
    </div>
</div>

<script type="text/javascript">
    //var img_documento_padrao = '';

    $(document).ready(function() {

        $("#cor").spectrum({
            preferredFormat: "hex",
            showInput: true,
            showPalette: true,
            cancelText: "Cancelar",
            chooseText: "Escolher",
            clearText: "Limpar seleção",
            noColorSelectedText: "Nenhuma cor selecionada",
            togglePaletteMoreText: "Mostrar paleta",
            togglePaletteLessText: "Ocultar paleta",
            palette: [
                ['#000', '#444', '#666', '#999', '#ccc', '#eee', '#fff'],
                ['#f44336', '#e91e63', '#9c27b0', '#673ab7', '#3f51b5', '#2196f3', '#03a9f4'],
                ['#4caf50', '#8bc34a', '#cddc39', '#ffeb3b', '#ffc107', '#ff9800', '#ff5722']
            ],
            change: function(color) {
                const hex = color.toHexString();
                // Salvar onde preferir (localStorage / AJAX)
                // localStorage.setItem('minha_cor_selecionada', hex);
            }
        });

        $('.imageupload').imageupload({
            allowedFormats: ["jpg", "jpeg", "png", "gif"],
            maxFileSizeKb: 3072
        });

        $('#logo_empresa').val('<?= $this->empresa ? $this->empresa['logo'] : '' ?>');
    });
</script>