<?php
$skyn = Zend_Registry::get('skin') ? Zend_Registry::get('skin') : 'padrao';
?>
<!doctype html>
<html lang="en" class="h-100">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="generator" content="Hugo 0.84.0">
  <title>Ouvidoria</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap4.min.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.7.1/css/buttons.dataTables.min.css">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-sweetalert/1.0.1/sweetalert.min.css">
  <!-- Latest compiled and minified CSS -->
  <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>

  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@ttskch/select2-bootstrap4-theme@x.x.x/dist/select2-bootstrap4.min.css">


  <link href="https://cdn.jsdelivr.net/npm/bootstrap4-datetimepicker@5.2.3/build/css/bootstrap-datetimepicker.min.css" rel="stylesheet">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/11.0.2/css/bootstrap-slider.min.css" />

  <!-- Favicons -->
  <link rel="icon" href="../../<?= $skyn ?>/favicon.ico">
  <style>
    :root {
      --dt-primary: <?= $this->empresa['cor'] ?? '#097f8c' ?>;
      --dt-active: color-mix(in srgb, var(--dt-primary) 80%, black 40%);
    }
  </style>
  <link rel="stylesheet" href=".../../../<?= $skyn ?>/principal.css?versao=1">

  <link href="../../img-upload/dist/css/bootstrap-imageupload.css" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/spectrum/1.8.1/spectrum.min.css">

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css">

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/dropzone@5.9.3/dist/min/dropzone.min.css">
  <!-- jQuery library -->
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
</head>

<body class="h-100">
  <nav class="navbar sticky-top bg-light flex-nowrap p-0 shadow navbar-expand-lg">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0">
      <button type="button" id="sidebarCollapse" class="btn text-primary mr-2">
        <i class="fa fa-bars"></i>
      </button>
      <img class="img-fluid" loading="lazy" src="<?= $this->empresa['logo'] ?>" alt="Logo do SISTEMA">
    </a>

    <ul class="navbar-nav ml-auto mr-2">
      <div class="full-screen-toolbar btn-toolbar mb-2 mb-md-0">
        <div class="btn-toolbar mb-2 mb-md-0">
          <button type="button" onclick="openFullscreen()" class="full-screen btn"><i class="fa fa-expand text-primary" aria-hidden="true"></i></button>
          <button type="button" onclick="closeFullscreen()" class="close-full-screen btn"><i class="fa fa-compress text-primary" aria-hidden="true"></i></button>
        </div>
      </div>
      <li class="nav-item dropdown text-nowrap">
        <a class="nav-link dropdown-toggle" title="<?= $this->usuario ?>" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-expanded="false">
          <i class="fa fa-user-circle-o"></i><span id="nome_usuario">&nbsp;<?= $this->usuario ?></span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item principal-link" href="#" data-src="../../index/novasenha"><i class="fa fa-key"></i>&nbsp;Alterar Senha</a>
          <a class="dropdown-item" href="../../index/logout"><i class="fa fa-sign-out"></i>&nbsp;Sair</a>
        </div>
      </li>
    </ul>
    <!--<ul class="navbar-nav px-3">
      <li class="nav-item text-nowrap">
        <a class="btn text-primary principal-link" data-src="../../agenda" href="#"><i class="fa fa-calendar"></i></a>
      </li>
    </ul>
    <ul class="navbar-nav px-3">
      <li class="nav-item text-nowrap">
        <a class="btn text-primary" href="../../index/logout"><i class="fa fa-sign-out"></i></a>
      </li>
    </ul-->
  </nav>
  <?php
  $modulo = Util::getController();
  ?>
  <!-- start wrapper -->
  <div class="wrapper">
    <nav class="sidebar active">
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a href="#" class="principal-link nav-link" data-menu-item="dashboard" data-src="../../dashboard">
              <i class="fa fa-line-chart" aria-hidden="true"></i>
              Dashboard
            </a>
          </li>
          <li class="nav-item">
            <a href="#" class="principal-link nav-link" data-menu-item="kanban" data-src="../../kanban">
              <i class="fa fa-clone" aria-hidden="true"></i>
              Kanban
            </a>
          </li>
          <li class="nav-item">
            <a href="#" class="principal-link nav-link" data-menu-item="consulta" data-src="../../consulta">
              <i class="fa fa-newspaper-o" aria-hidden="true"></i>
              Consulta
            </a>
          </li>
        </ul>
        <ul class="nav flex-column mb-2">
          <? if ($this->permissao == 1): ?>
            <li class="nav-item">
              <a href="#" class="principal-link nav-link" data-menu-item="usuario" data-src="../../usuario">
                <i class="fa fa-user-circle-o" aria-hidden="true"></i>
                Usuários
              </a>
            </li>
          <? endif; ?>
          <li class="nav-item">
            <a href="#" class="principal-link nav-link" data-menu-item="empresa" data-src="../../empresa">
              <i class="fa fa-cogs" aria-hidden="true"></i>
              Empresa
            </a>
          </li>
        </ul>
      </div>
    </nav>

    <div id="content" class="h-100">